### ISSUE TITLE
dependency libicu57 is not available; Its replaced by libicu63

### ISSUE THREAD

**Issue by Pradeep39** [piksel/phantomjs-raspberrypi#10]
Installing dependencies is returning an error. 
```sudo apt install libicu57 libssl1.0.2 gstreamer0.10-base fontconfig freetype2```

Package libicu57 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu57' has no installation candidate

**Comment by piksel** [comment]
You are using `buster` which I have no precompiled binaries for. Only `Jessie` and `Stretch` are supported  right now. I might attempt a new compile soon, though.

**Comment by Pradeep39** [comment]
Thank You @piksel . I was able to work around the issue by installing the deb package at https://packages.debian.org/stretch/armhf/libicu57/download

i just downloaded it and double clicked on it to install libicu57 dependency and now the phantomjs works. Thought this might be useful for others who wish to make your binary work for ```Buster```

**Comment by piksel** [comment]
That's nice! It should work, but might lead to some conflicts. I would also advice using the Raspbian packages (if you are using Raspbian), they might be equivalent to the Debian-armhf ones though:
http://archive.raspbian.org/raspbian/pool/main/i/icu/icu_57.1-6%2Bdeb9u2.debian.tar.xz

**Comment by piksel** [comment]
I created a new release, which includes the libicu57 library. Hopefully this will be useful for someone.
https://github.com/piksel/phantomjs-raspberrypi/releases/tag/v2.1.1-r

**Comment by IntegersOfK** [comment]
I am running Grafana on my Raspberry Pi 4, and this new release still gave me `error while loading shared libraries: libicui18n.so.57` which I was able to solve by downloading and installing this package:

```wget http://archive.raspbian.org/raspbian/pool/main/i/icu/libicu57_57.1-6%2Bdeb9u3_armhf.deb`
sudo dpkg -i libicu57_57.1-6+deb9u3_armhf.deb```

After that I just copied this release's `phantomjs` it into my Grafana `tools/phantomjs/phantomjs` directory and everything works to render my charts as an image. Thank you very much!

**Comment by piksel** [comment]
@IntegersOfK that's odd. The 'phantomjs' file should not be the binary in that release, it's just a script that launches the phantomjs-bin. So I guess you didn't get the right release package? It doesn't matter though, using that package is basically the same as the above.
