### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by kotrfa** [piksel/phantomjs-raspberrypi#2]
Thank you for your great work!

I was personally aware of having dependencies for PhantomJS, but someone might be messing this information. Could you add them to README? I think it's: ``gstreamer0.10-base``, ``fontconfig``, and ``freetype2``. All available in official repos (at least in Arch Linux).

**Comment by piksel** [comment]
Had all packages before compiling so I didn't notice. Thanks!

**Comment by kotrfa** [comment]
Welcome. And thank you for your work :) . It helped me a lot.
