### ISSUE TITLE
E: Package 'libssl1.0.0' has no installation candidate

### ISSUE THREAD

**Issue by cnazev** [piksel/phantomjs-raspberrypi#6]
libssl1.0.2 is already the newest version (1.0.2l-2+deb9u1).
libssl1.1 is already the newest version (1.1.0f-3+deb9u1).

raspberrypi 3b

**Comment by cnazev** [comment]
sorry closed

**Comment by piksel** [comment]
For anyone else finding this issue:
Use the [stretch branch](https://github.com/piksel/phantomjs-raspberrypi/tree/stretch).
