### ISSUE TITLE
Trying to install dependency list

### ISSUE THREAD

**Issue by tvl83** [piksel/phantomjs-raspberrypi#8]
I am getting the following error:
![image](https://user-images.githubusercontent.com/141966/34801453-6f498ca2-f62e-11e7-9806-37c488220029.png)

**Comment by piksel** [comment]
`gstreamer0.10-base` and `freetype2` are two packages that need to be separated by a space, try this:
```sudo apt-get install gstreamer0.10-base freetype2```
